import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import styles from './page.module.css'

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <nav className={styles.navbar}>
                    <div className={styles.logo}>STRATEGY<span>CO</span></div>

                    <ul className={styles.navlinks}>
                        <li><Link href="/" className={styles.navlinks}>Home</Link></li>
                        <li><Link href="/about" className={styles.navlinks}>About</Link></li>
                        <li><Link href="/services" className={styles.navlinks}>Services</Link></li>
                        <li><Link href="/portfolio" className={styles.navlinks}>Portfolio</Link></li>
                        <li><Link href="/contact" className={styles.navlinks}>Contact</Link></li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}
