import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
          crossOrigin="anonymous"
        />

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous"></script>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">

          <div className="row mt-3">
            <div className="col-2 border border-danger d-flex justify-content-center align-items-center">logo</div>
            <div className="col border border-danger  d-flex justify-content-center align-items-center">
              <nav className="navbar navbar-expand-lg bg-body-tertiary">
                <div className="container-fluid">
                  <div className="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul className="navbar-nav">
                      <li className="nav-item">
                        <Link className="nav-link active" aria-current="page" href="/">Home</Link>
                      </li>
                      <li className="nav-item">
                        <Link className="nav-link active" aria-current="page" href="/contact">Contact</Link>
                      </li>
                      <li className="nav-item">
                        <Link className="nav-link active" aria-current="page" href="/about">About</Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
            </div>
          </div>

          <div className="row">
            <div className="col-3 border border-danger">
              <div className="sidebar border-end">
                <div className="sidebar-header border-bottom">
                  <div className="sidebar-brand">CoreUI</div>
                </div>
                <ul className="sidebar-nav">
                  <li className="nav-title">Nav Title</li>
                  <li className="nav-item">
                    <a className="nav-link active" href="#">
                      <i className="nav-icon cil-speedometer"></i> Nav item
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      <i className="nav-icon cil-speedometer"></i> With badge
                      <span className="badge bg-primary ms-auto">NEW</span>
                    </a>
                  </li>
                  <li className="nav-item nav-group show">
                    <a className="nav-link nav-group-toggle" href="#">
                      <i className="nav-icon cil-puzzle"></i> Nav dropdown
                    </a>
                    <ul className="nav-group-items">
                      <li className="nav-item">
                        <a className="nav-link" href="#">
                          <span className="nav-icon"><span className="nav-icon-bullet"></span></span> Nav dropdown item
                        </a>
                      </li>
                      <li className="nav-item">
                        <a className="nav-link" href="#">
                          <span className="nav-icon"><span className="nav-icon-bullet"></span></span> Nav dropdown item
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li className="nav-item mt-5">
                    <a className="nav-link" href="#">
                      <i className="nav-icon cil-cloud-download"></i> Download CoreUI</a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      <i className="nav-icon cil-layers"></i> Try CoreUI
                      <strong>PRO</strong>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="col border border-danger d-flex justify-content-center align-items-center">{children}</div>
          </div>

          <div className="row">
            <div className="col border border-danger d-flex justify-content-center align-items-center">footer</div>
          </div>
        </div>

      </body>
    </html>
  );
}
